### ISSUE TITLE
Wordpress Droplet

### ISSUE THREAD

**Issue by oliver-jun** [itcarsales/dropletTools#1]
I found an issue in your script, its working fine if you using a domain without a dash like example.com
when you using a domain like example-de.com you getting an syntax error.
How to fix it? 

ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-jundb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci' at line 1

**Comment by itcarsales** [comment]
SQL needs backticks to escape the "-" when making sql queries.  My current script doesnt account for this, but thanks for the tip!

for now, you could add that to the script manually and rerun.....otherwise there is no immediate fix for that exact scenario.

**Comment by oliver-jun** [comment]
Thanks for the info 👍 its working now.

**Comment by itcarsales** [comment]
allowing hyphens in the database name can cause problems with access with proper quotes, which an get confusing for me to keep track of.  Instead, i added code to remove them,  here is the logic that I use...but I do not use many non-letter characters in my domains so I do not know what is allowed and what is not.  I can always add more sed later to remove additional characters as needed:

echo && read -p "Please enter your new domain name (example.com):" newDomain && echo
mysqlUser=$(echo $newDomain | sed 's/\..*$//' | sed 's/\-//g')
mysqlDB=$mysqlUser"db"
echo $newDomain
echo $mysqlUser
echo $mysqlDB
