### ISSUE TITLE
LetsEncrypt renew (auto)?

### ISSUE THREAD

**Issue by oliver-jun** [itcarsales/dropletTools#3]
Hey, i just found out there is no cronjob for an automatic renew of my letsencrypt certificate.
Is there a tutorial to set it up with your script?

Thanks!

**Comment by itcarsales** [comment]
There was, but it was under the user cron by mistake.  I added a script and a root task at cron.d to hopefully take care of future renewals.

**Comment by itcarsales** [comment]
remove the third user crontab using crontab -e
then to repair an existing server use:

echo "0 0 * * * /root/SSLrenew.sh >> /var/log/SSLrenew.log" | sudo crontab -

cat << EOF > "$HOME/SSLrenew.sh"
#!/bin/bash
date +%d-%m-%y/%H:%M:%S
letsencrypt renew
/usr/sbin/service nginx reload
echo "----------------------------------------"
EOF

sudo mv $HOME/SSLrenew.sh /root/SSLrenew.sh 
sudo chown -R root /root/SSLrenew.sh
sudo chmod +x /root/SSLrenew.sh

**Comment by itcarsales** [comment]
FYI - this would be simpler if Ubuntu/Mint supported a newer version of certbot.  There are numerous guides for installing their repo and updating, but then I had a whole separate set of problems.  If you ever find or code a better solution, please let me know!!!
